secrets:
    my_jwt_secret:
      file: ./my_jwt_secret.key
services:

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: tree
      POSTGRES_PASSWORD: papa
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    ports:
      - "5001:8000"
    secrets:
      - my_jwt_secret
    environment:
      DATABASE_URL: "postgresql://tree:papa@db:5432/auth"
      SECRET_KEY_FILE: /run/secrets/my_jwt_secret
    depends_on:
      - db
    networks:
      - default

  post-service:
    build: ./post-service
    ports:
      - "5002:8000"
    secrets:
      - my_jwt_secret
    environment:
      DATABASE_URL: "postgresql://tree:papa@db:5432/post"
      SECRET_KEY_FILE: /run/secrets/my_jwt_secret
    depends_on:
      - db
    networks:
      - default

volumes:
  postgres_data:
