services:

  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: tree
      POSTGRES_PASSWORD: papa
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    ports:
      - "5001:8000"
    environment:
      DATABASE_URL: "postgresql://tree:papa@db:5432/mydatabase"  # Подключение к БД внутри Docker
      SECRET_KEY: "pBUgw40GXBWiWsbtbQajxyy-xtAQyFd-c4G3RJBj0Dw" # Секретный ключ JWT
    depends_on:
      - db
    networks:
      - default

  post-service:
    build: ./post-service
    ports:
      - "5002:8000"
    environment:
      DATABASE_URL: "postgresql://tree:papa@db:5432/mydatabase"  #  Та же БД
      SECRET_KEY: "pBUgw40GXBWiWsbtbQajxyy-xtAQyFd-c4G3RJBj0Dw" #  Тот же секретный ключ!  todo: Docker Secrets в production
    depends_on:
      - db
    networks:
      - default

volumes:
  postgres_data:
